<?php /** @var ArmMage\LearningMagento\Block\Article $block */ ?>
<form action="<?php echo $block->getFormAction() ?>" method="post">
    <label for="title">Title</label><br>
    <input name="title" id='title' type="text">
    <label for="description">Description</label><br>

    <input name="description" id="description" type="text">
    <label for="status">Status</label><br>

    <input name="status" id="status" type="radio" value="1" checked="checked" >
    <input type="submit" value="Create blog">
</form>
